/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ErrorLog {
  'errorMessage' : string,
  'printer' : [] | [string],
  'timestamp' : bigint,
}
export interface LabelConfig {
  'height' : bigint,
  'font' : string,
  'centerContents' : boolean,
  'textSize' : bigint,
  'horizontalSpacing' : bigint,
  'barcodePositionX' : bigint,
  'barcodePositionY' : bigint,
  'textPositionX' : bigint,
  'textPositionY' : bigint,
  'barcodeType' : string,
  'customText' : string,
  'barcodeWidthScale' : bigint,
  'margin' : bigint,
  'barcodeHeight' : bigint,
  'width' : bigint,
}
export interface PrintRecord {
  'labelType' : string,
  'printer' : string,
  'serialNumber' : string,
  'timestamp' : bigint,
}
export interface Printer {
  'status' : string,
  'name' : string,
  'connectionType' : string,
}
export interface TitleMapping { 'title' : string, 'prefix' : string }
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addErrorLog' : ActorMethod<[string, [] | [string]], undefined>,
  'addPrintRecord' : ActorMethod<[string, string, string], undefined>,
  'addPrinter' : ActorMethod<[string, string], undefined>,
  'addSinglePrefix' : ActorMethod<[string], undefined>,
  'addTitleMapping' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticate' : ActorMethod<[string], boolean>,
  'clearErrorLogs' : ActorMethod<[], undefined>,
  'clearPrintHistory' : ActorMethod<[], undefined>,
  'getAllErrorLogs' : ActorMethod<[], Array<ErrorLog>>,
  'getAllLabelConfigs' : ActorMethod<[], Array<LabelConfig>>,
  'getAllLabelConfigsPreview' : ActorMethod<[], Array<LabelConfig>>,
  'getAllPrintRecords' : ActorMethod<[], Array<PrintRecord>>,
  'getAllPrinters' : ActorMethod<[], Array<Printer>>,
  'getAllTitleMappings' : ActorMethod<[], Array<TitleMapping>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLabelConfig' : ActorMethod<[string], LabelConfig>,
  'getLabelConfigPreview' : ActorMethod<[string], LabelConfig>,
  'getNewDualLabelCount' : ActorMethod<[], bigint>,
  'getPrefixes' : ActorMethod<[], Array<string>>,
  'getPrinter' : ActorMethod<[string], Printer>,
  'getTitleByPrefix' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'health' : ActorMethod<[], boolean>,
  'incrementNewDualLabelCount' : ActorMethod<[], bigint>,
  'initializeDefaultTitles' : ActorMethod<[], undefined>,
  'isAuthenticatedQuery' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logout' : ActorMethod<[], undefined>,
  'removeSpecificPrefix' : ActorMethod<[string], undefined>,
  'removeTitleMapping' : ActorMethod<[string], undefined>,
  'resetAllCounters' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLabelConfig' : ActorMethod<[string, LabelConfig], undefined>,
  'setPrefixes' : ActorMethod<[Array<string>], undefined>,
  'updatePrinterStatus' : ActorMethod<[string, string], undefined>,
  'validateBarcode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];