/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ErrorLog = IDL.Record({
  'errorMessage' : IDL.Text,
  'printer' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
});
export const LabelConfig = IDL.Record({
  'height' : IDL.Nat,
  'font' : IDL.Text,
  'centerContents' : IDL.Bool,
  'textSize' : IDL.Nat,
  'horizontalSpacing' : IDL.Nat,
  'barcodePositionX' : IDL.Nat,
  'barcodePositionY' : IDL.Nat,
  'textPositionX' : IDL.Nat,
  'textPositionY' : IDL.Nat,
  'barcodeType' : IDL.Text,
  'customText' : IDL.Text,
  'barcodeWidthScale' : IDL.Nat,
  'margin' : IDL.Nat,
  'barcodeHeight' : IDL.Nat,
  'width' : IDL.Nat,
});
export const PrintRecord = IDL.Record({
  'labelType' : IDL.Text,
  'printer' : IDL.Text,
  'serialNumber' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Printer = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'connectionType' : IDL.Text,
});
export const TitleMapping = IDL.Record({
  'title' : IDL.Text,
  'prefix' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addErrorLog' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'addPrintRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addPrinter' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSinglePrefix' : IDL.Func([IDL.Text], [], []),
  'addTitleMapping' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'clearErrorLogs' : IDL.Func([], [], []),
  'clearPrintHistory' : IDL.Func([], [], []),
  'getAllErrorLogs' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
  'getAllLabelConfigs' : IDL.Func([], [IDL.Vec(LabelConfig)], ['query']),
  'getAllPrintRecords' : IDL.Func([], [IDL.Vec(PrintRecord)], ['query']),
  'getAllPrinters' : IDL.Func([], [IDL.Vec(Printer)], ['query']),
  'getAllTitleMappings' : IDL.Func([], [IDL.Vec(TitleMapping)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLabelConfig' : IDL.Func([IDL.Text], [LabelConfig], ['query']),
  'getNewDualLabelCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPrefixes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPrinter' : IDL.Func([IDL.Text], [Printer], ['query']),
  'getTitleByPrefix' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'health' : IDL.Func([], [IDL.Bool], ['query']),
  'incrementNewDualLabelCount' : IDL.Func([], [IDL.Nat], []),
  'initializeDefaultTitles' : IDL.Func([], [], []),
  'isAuthenticatedQuery' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logout' : IDL.Func([], [], []),
  'removeSpecificPrefix' : IDL.Func([IDL.Text], [], []),
  'removeTitleMapping' : IDL.Func([IDL.Text], [], []),
  'resetAllCounters' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLabelConfig' : IDL.Func([IDL.Text, LabelConfig], [], []),
  'setPrefixes' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updatePrinterStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'validateBarcode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ErrorLog = IDL.Record({
    'errorMessage' : IDL.Text,
    'printer' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
  });
  const LabelConfig = IDL.Record({
    'height' : IDL.Nat,
    'font' : IDL.Text,
    'centerContents' : IDL.Bool,
    'textSize' : IDL.Nat,
    'horizontalSpacing' : IDL.Nat,
    'barcodePositionX' : IDL.Nat,
    'barcodePositionY' : IDL.Nat,
    'textPositionX' : IDL.Nat,
    'textPositionY' : IDL.Nat,
    'barcodeType' : IDL.Text,
    'customText' : IDL.Text,
    'barcodeWidthScale' : IDL.Nat,
    'margin' : IDL.Nat,
    'barcodeHeight' : IDL.Nat,
    'width' : IDL.Nat,
  });
  const PrintRecord = IDL.Record({
    'labelType' : IDL.Text,
    'printer' : IDL.Text,
    'serialNumber' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Printer = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'connectionType' : IDL.Text,
  });
  const TitleMapping = IDL.Record({ 'title' : IDL.Text, 'prefix' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addErrorLog' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'addPrintRecord' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addPrinter' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSinglePrefix' : IDL.Func([IDL.Text], [], []),
    'addTitleMapping' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'clearErrorLogs' : IDL.Func([], [], []),
    'clearPrintHistory' : IDL.Func([], [], []),
    'getAllErrorLogs' : IDL.Func([], [IDL.Vec(ErrorLog)], ['query']),
    'getAllLabelConfigs' : IDL.Func([], [IDL.Vec(LabelConfig)], ['query']),
    'getAllPrintRecords' : IDL.Func([], [IDL.Vec(PrintRecord)], ['query']),
    'getAllPrinters' : IDL.Func([], [IDL.Vec(Printer)], ['query']),
    'getAllTitleMappings' : IDL.Func([], [IDL.Vec(TitleMapping)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLabelConfig' : IDL.Func([IDL.Text], [LabelConfig], ['query']),
    'getNewDualLabelCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPrefixes' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPrinter' : IDL.Func([IDL.Text], [Printer], ['query']),
    'getTitleByPrefix' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'health' : IDL.Func([], [IDL.Bool], ['query']),
    'incrementNewDualLabelCount' : IDL.Func([], [IDL.Nat], []),
    'initializeDefaultTitles' : IDL.Func([], [], []),
    'isAuthenticatedQuery' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logout' : IDL.Func([], [], []),
    'removeSpecificPrefix' : IDL.Func([IDL.Text], [], []),
    'removeTitleMapping' : IDL.Func([IDL.Text], [], []),
    'resetAllCounters' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLabelConfig' : IDL.Func([IDL.Text, LabelConfig], [], []),
    'setPrefixes' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updatePrinterStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'validateBarcode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };