/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Printer {
    status: string;
    name: string;
    connectionType: string;
}
export interface ErrorLog {
    errorMessage: string;
    printer?: string;
    timestamp: bigint;
}
export interface LabelConfig {
    height: bigint;
    font: string;
    centerContents: boolean;
    textSize: bigint;
    horizontalSpacing: bigint;
    barcodePositionX: bigint;
    barcodePositionY: bigint;
    textPositionX: bigint;
    textPositionY: bigint;
    barcodeType: string;
    customText: string;
    barcodeWidthScale: bigint;
    margin: bigint;
    barcodeHeight: bigint;
    width: bigint;
}
export interface TitleMapping {
    title: string;
    prefix: string;
}
export interface PrintRecord {
    labelType: string;
    printer: string;
    serialNumber: string;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addErrorLog(errorMessage: string, printer: string | null): Promise<void>;
    addPrintRecord(serialNumber: string, labelType: string, printer: string): Promise<void>;
    addPrinter(name: string, connectionType: string): Promise<void>;
    addSinglePrefix(prefix: string): Promise<void>;
    addTitleMapping(prefix: string, title: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticate(password: string): Promise<boolean>;
    clearErrorLogs(): Promise<void>;
    clearPrintHistory(): Promise<void>;
    getAllErrorLogs(): Promise<Array<ErrorLog>>;
    getAllLabelConfigs(): Promise<Array<LabelConfig>>;
    getAllPrintRecords(): Promise<Array<PrintRecord>>;
    getAllPrinters(): Promise<Array<Printer>>;
    getAllTitleMappings(): Promise<Array<TitleMapping>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLabelConfig(name: string): Promise<LabelConfig>;
    getNewDualLabelCount(): Promise<bigint>;
    getPrefixes(): Promise<Array<string>>;
    getPrinter(name: string): Promise<Printer>;
    getTitleByPrefix(prefix: string): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    health(): Promise<boolean>;
    incrementNewDualLabelCount(): Promise<bigint>;
    initializeDefaultTitles(): Promise<void>;
    isAuthenticatedQuery(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    logout(): Promise<void>;
    removeSpecificPrefix(prefixToRemove: string): Promise<void>;
    removeTitleMapping(prefixToRemove: string): Promise<void>;
    resetAllCounters(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveLabelConfig(name: string, config: LabelConfig): Promise<void>;
    setPrefixes(newPrefixes: Array<string>): Promise<void>;
    updatePrinterStatus(name: string, status: string): Promise<void>;
    validateBarcode(barcode: string): Promise<boolean>;
}
import type { ErrorLog as _ErrorLog, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addErrorLog(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addErrorLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addErrorLog(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addPrintRecord(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrintRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrintRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async addPrinter(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrinter(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrinter(arg0, arg1);
            return result;
        }
    }
    async addSinglePrefix(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSinglePrefix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSinglePrefix(arg0);
            return result;
        }
    }
    async addTitleMapping(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTitleMapping(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTitleMapping(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticate(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticate(arg0);
            return result;
        }
    }
    async clearErrorLogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearErrorLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearErrorLogs();
            return result;
        }
    }
    async clearPrintHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPrintHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPrintHistory();
            return result;
        }
    }
    async getAllErrorLogs(): Promise<Array<ErrorLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllErrorLogs();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllErrorLogs();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLabelConfigs(): Promise<Array<LabelConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLabelConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLabelConfigs();
            return result;
        }
    }
    async getAllPrintRecords(): Promise<Array<PrintRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrintRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrintRecords();
            return result;
        }
    }
    async getAllPrinters(): Promise<Array<Printer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrinters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrinters();
            return result;
        }
    }
    async getAllTitleMappings(): Promise<Array<TitleMapping>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTitleMappings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTitleMappings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLabelConfig(arg0: string): Promise<LabelConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabelConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabelConfig(arg0);
            return result;
        }
    }
    async getNewDualLabelCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewDualLabelCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewDualLabelCount();
            return result;
        }
    }
    async getPrefixes(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrefixes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrefixes();
            return result;
        }
    }
    async getPrinter(arg0: string): Promise<Printer> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinter(arg0);
            return result;
        }
    }
    async getTitleByPrefix(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTitleByPrefix(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTitleByPrefix(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async health(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.health();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.health();
            return result;
        }
    }
    async incrementNewDualLabelCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementNewDualLabelCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementNewDualLabelCount();
            return result;
        }
    }
    async initializeDefaultTitles(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeDefaultTitles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeDefaultTitles();
            return result;
        }
    }
    async isAuthenticatedQuery(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthenticatedQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthenticatedQuery();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async removeSpecificPrefix(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSpecificPrefix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSpecificPrefix(arg0);
            return result;
        }
    }
    async removeTitleMapping(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTitleMapping(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTitleMapping(arg0);
            return result;
        }
    }
    async resetAllCounters(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllCounters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllCounters();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveLabelConfig(arg0: string, arg1: LabelConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLabelConfig(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLabelConfig(arg0, arg1);
            return result;
        }
    }
    async setPrefixes(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPrefixes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPrefixes(arg0);
            return result;
        }
    }
    async updatePrinterStatus(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrinterStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrinterStatus(arg0, arg1);
            return result;
        }
    }
    async validateBarcode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateBarcode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateBarcode(arg0);
            return result;
        }
    }
}
function from_candid_ErrorLog_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ErrorLog): ErrorLog {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    errorMessage: string;
    printer: [] | [string];
    timestamp: bigint;
}): {
    errorMessage: string;
    printer?: string;
    timestamp: bigint;
} {
    return {
        errorMessage: value.errorMessage,
        printer: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.printer)),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ErrorLog>): Array<ErrorLog> {
    return value.map((x)=>from_candid_ErrorLog_n5(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
